#服务请求地址
url:
  dmp: http://10.199.87.120:32050/api-ibms-dmp
  monitor: http://10.199.87.120:32050/api-ibms-monitor
  alarmUrl: http://10.199.87.120:32050/api-ibms-alarm
  alarmWebSocket: ws://10.199.87.120:32050/ws-ibms-alarm/webSocketServer

  iotProject: http://10.8.14.155:18858
  iotWebSocket: ws://10.8.14.155:18888/websocket

spring:
  redis:
    #    sdk
    primary:
      #      sentinel:
      #        master: mymaster
      #        nodes:
      host: 10.8.14.155
      port: 16379
      timeout: 10000
      database: 6
    #      control
    secondary:
      host: 10.8.14.155
      port: 16379

  kafka:
    sdk:
      bootstrapServers: 10.199.87.63:19092,10.199.87.79:19092,10.199.87.85:19092
    alarm:
      bootstrapServers: ${spring.kafka.sdk.bootstrap-servers}
    control:
      bootstrapServers: ${spring.kafka.sdk.bootstrap-servers}

  datasource:
    url: jdbc:mysql://10.8.14.155:3306/huiyun_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false

