#服务请求地址
url:
  dmp: http://10.199.87.120:32050/api-ibms-dmp
  monitor: http://10.199.87.120:32050/api-ibms-monitor
  alarmUrl: http://10.199.87.120:32050/api-ibms-alarm
  alarmWebSocket: ws://10.199.87.120:32050/ws-ibms-alarm/webSocketServer

  iotProject: http://127.0.0.1:18858
  iotWebSocket: ws://127.0.0.1:18888/websocket

spring:
  redis:
    #    sdk
    primary:
      sentinel:
        master: mymaster
        nodes: 10.199.87.62:26379,10.199.87.70:26379,10.199.87.78:26379
      password: hdwaredis0912
      timeout: 10000000
      database: 6
    #      control
    secondary:
      host: 127.0.0.1
      port: 16379

  kafka:
    sdk:
      bootstrapServers: 10.199.87.63:19092,10.199.87.79:19092,10.199.87.85:19092
    alarm:
      bootstrapServers: ${spring.kafka.sdk.bootstrap-servers}
    control:
      bootstrapServers: ${spring.kafka.sdk.bootstrap-servers}

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huiyun_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false

