#呼市赛罕，10.27.8.45
group:
  control:
    host: 10.199.205.60
    code: WD
    project:
      #------------------iot使用项目ID 需更改
      id: Pj1101050001
      #------------------iot使用项目ID，不包含PJ 需更改
      iotid: 1101050001

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.199.205.60:3306/hdwa_ibms_alarm?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    username: root
    password: hdwadbajd0520
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5  # 初始化大小
    min-idle: 5  # 最小
    max-active: 20  # 最大
    max-wait: 60000  # 配置获取连接等待超时的时间
    time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
    validationQuery: select 'x'
    test-while-idle: true  # 当连接空闲时，是否执行连接测试
    test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
    test-on-return: false  # 在连接归还到连接池时是否测试该连接
    filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
    MaxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 50
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.slowSqlMillis=500;druid.stat.logSlowSql=true;config.decrypt=false
  #redis配置
  redis:
    host: ${group.control.host}
    port: 16379
    password:
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never  # always never
      comment-prefix: '#'
  kafka:
    ## 是否开启kafka
    enable: true
    #------------------kafka地址 需要修改
    bootstrapServers: 10.199.87.63:19092,10.199.87.79:19092,10.199.87.85:19092
    producer:
      # 发生错误后，消息重发的次数。
      retries: 2
      #当有多个消息需要被发送到同一个分区时，生产者会把它们放在同一个批次里。该参数指定了一个批次可以使用的内存大小，按照字节数计算。
      batch-size: 65536
      # 设置生产者内存缓冲区的大小。
      buffer-memory: 33554432
      acks: 1
      edgeTopic: control.edge2control
    consumer:
      # 自动提交的时间间隔 在spring boot 2.X 版本中这里采用的是值的类型为Duration 需要符合特定的格式，如1S,1M,2H,5D
      auto-commit-interval: 1S
      # 该属性指定了消费者在读取一个没有偏移量的分区或者偏移量无效的情况下该作何处理：
      # latest（默认值）在偏移量无效的情况下，消费者将从最新的记录开始读取数据（在消费者启动之后生成的记录）
      # earliest ：在偏移量无效的情况下，消费者将从起始位置读取分区的记录
      auto-offset-reset: latest
      # 是否自动提交偏移量，默认值是true,为了避免出现重复数据和数据丢失，可以把它设置为false,然后手动提交偏移量
      enable-auto-commit: false
      #------------------后缀为项目id 需要修改
      group-id: zkt-contorl-project-${group.control.project.id}
      topics: control.control2edge
      heartbeat-interval: 10S
    listener:
      # 在侦听器容器中运行的线程数。
      concurrency: 5
      #listner负责ack，每调用一次，就立即commit
      ack-mode: manual_immediate
      missing-topics-fatal: false
    properties:
      session:
        timeout:
          ms: 60000
      max:
        poll:
          interval:
            ms: 600000

#------------------ mqtt 需要更改
mqtt:
  hostUrl: tcp://10.199.87.72:1893
  username: admin
  password: public
  client-id: zkt-contorl-project-${group.control.project.id}
  cleanSession: true
  reconnect: true
  timeout: 100
  keepAlive: 100
  isOpen: true
  qos: 1

# 报警服务
remote:
  ibms-alarm:
    # ------------------需要更改，程序端口
    server-url:  10.199.87.67:8855
    # 推送消息时，是否会开启压缩，true-压缩 false-不压缩
    compress: false
    # ------------------需要更改
    host: 10.199.87.75
    # ------------------需要更改，netty端口
    port: 8825

  # IOT程序
  iot:
    # iot-project服务
    project:
      # ------------------需要更改，修改其中的项目ID和ip、port，其中port为websocket的端口，切记不是服务端口
      websocket: ws://127.0.0.1:30019/websocket?projectId=1301080090&type=pointset,iot&getFullData=true

      # IOT程序
      iot:
        # iot-collect 服务（无用）

    collect:
      # 是否启用collect服务的netty客户端,true-启用
      enable: false
      # iot-collect 服务的ip
      host: 0.0.0.0
      # iot-collect 服务的收数端口，切记不是服务端口
      port: 0
config:
  # ------------------标识哪个接团 比如万达使用WD，需修改
  group-code: WD
  # ------------------项目ID，需修改
  project-id: Pj1101050001
  # ------------------iot数据汇总所使用的项目ID，切记不包含Pj，需修改
  building: 1101050001

system:
  id: system  #默认用户表示 ，用于报警记录的创建人

alarm:
  get:
    all:
      alarmdefine:
        cron: 0 0 23 * * ?   #每天23点全量更新一次报警定义