#服务请求地址
url:
  #  dmp: http://127.0.0.1:9805
  dmp: http://10.199.208.69:32050/api-ibms-dmp
  monitor: http://10.199.208.69:32050/api-ibms-monitor
  alarmUrl: http://10.199.208.69:32050/api-ibms-alarm
  alarmWebSocket: ws://10.199.208.69:32050/ws-ibms-alarm/webSocketServer

  iotProject: http://10.199.205.79:18858
  iotWebSocket: ws://10.199.205.79:18888/websocket

spring:
  #  redis
  redis:
    #    sdk
    primary:
      host: 10.199.205.79
      port: 16379
      timeout: 10000
      database: 6
    #      control
    secondary:
      host: 10.199.205.79
      port: 16379

  # kafka
  kafka:
    sdk:
      bootstrap-servers: 10.199.205.61:9092
    alarm:
      bootstrap-servers: ${spring.kafka.sdk.bootstrap-servers}
    control:
      bootstrap-servers: ${spring.kafka.sdk.bootstrap-servers}

  # mysql
  datasource:
    url: jdbc:mysql://10.199.205.79:3306/huiyun?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false

