#服务请求地址
url:
  dmp: http://jd-api.wandacm.cn/api-ibms-dmp
  monitor: http://jd-api.wandacm.cn/api-ibms-monitor
  alarmUrl: http://jd-api.wandacm.cn/api-ibms-alarm
  alarmWebSocket: ws://jd-api.wandacm.cn/ws-ibms-alarm/webSocketServer

  iotProject: http://127.0.0.1:18858
  iotWebSocket: ws://127.0.0.1:18888/websocket

spring:
  redis:
    #    sdk
    primary:
      #      sentinel:
      #        master: mymaster
      #        nodes:
      host: 127.0.0.1
      port: 16379
      timeout: 1000000
      database: 5
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 16
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
          # 当连接池耗尽时，等待连接返回的最大时间，单位毫秒；-1表示永不超时
          max-wait: -1
    #      control
    secondary:
      host: 127.0.0.1
      port: 16379
      timeout: 1000000
      database: 0
      jedis:
        pool:
          # 连接池最大连接数（使用负值表示没有限制）
          max-active: 16
          # 连接池中的最大空闲连接
          max-idle: 8
          # 连接池中的最小空闲连接
          min-idle: 0
          # 当连接池耗尽时，等待连接返回的最大时间，单位毫秒；-1表示永不超时
          max-wait: -1

  kafka:
    sdk:
      bootstrapServers: 172.27.142.111:9092,172.27.142.136:9092,172.27.142.221:9092
    alarm:
      bootstrapServers: ${spring.kafka.sdk.bootstrap-servers}
    control:
      bootstrapServers: ${spring.kafka.sdk.bootstrap-servers}

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/huiyun_new?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false