server:
  port: 8863
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 10000
    min-spare-threads: 100

spring:
  redis:
    host: 10.199.205.81
    port: 6379
    password: hdwaredis0912jd
    database: 5

#项目信息
project:
  id: Pj4401830001
  groupCode: WD

#数据文件目录
dirName:
  config: config
  point: point
  physicalWorld: physical_world
  ibmsLogicalGroup: ibms_logical_group
  ibmsPhysicalWorld: ibms_physical_world
  temp: temp

#服务请求地址
url:
  dmp: http://127.0.0.1:9805
  monitor: http://10.199.87.73:9930/zkt-monitor
  alarmUrl: http://10.199.87.73:9930/ibms-alarm
  iotProject: http://10.53.32.205:18852
  iotWebSocket: ws://10.53.32.205:30019/websocket
  alarmWebSocket: ws://10.199.87.67:8825/webSocketServer