server:
  port: 7777
  tomcat:
    accept-count: 1000
    max-threads: 1000
    max-connections: 10000
    min-spare-threads: 100

#项目信息
project:
  groupCode: WD

#数据文件目录
dirName:
  config: config
  point: point
  physicalWorld: physical_world
  ibmsLogicalGroup: ibms_logical_group
  ibmsPhysicalWorld: ibms_physical_world
  temp: temp

spring:
  profiles:
    active: dev
  kafka:
    #生产者配置
    producer:
      retries: 2
      batch-size: 65536
      properties:
        linger:
          #提交延时 当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka   linger.ms为0表示每接收到一条消息就提交给kafka,这时候batch-size其实就没用了
          ms: 1000
      #生产端缓冲区大小
      buffer-memory: 33554432
      #序列化
      value-serializer: com.hdwa.sdk.kafka.MsgJsonSerializer
      acks: all
    consumer:
      properties:
        topic: dmpToSdk
        group:
          #默认的消费组ID，设置成不一样的订阅者每个才能收到消息
          id: sdk-#{ T(java.util.UUID).randomUUID().toString() }
        session:
          timeout:
            #消费会话超时时间(超过这个时间consumer没有发送心跳,就会触发rebalance操作)
            ms: 120000
        request:
          timeout:
            #消费请求超时时间
            ms: 180000
      #反序列化
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      #earliest 在各分区下有提交的offset时：从offset处开始消费  在各分区下无提交的offset时：从头开始消费
      #latest 在各分区下有提交的offset时：从offset处开始消费  在各分区下无提交的offset时：从最新的数据开始消费
      auto-offset-reset: latest